version: "3"
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - api-auth

  api-auth:
    build: ./api-auth
    ports:
      - "3001:3001"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_SECRET=${JWT_SECRET}

  api-business:
    build: ./api-business
    ports:
      - "3002:3002"
    environment:
      - JWT_SECRET=${JWT_SECRET}

  nextjs-front:
    build: ./next-front
    restart: always
    ports:
      - "3030:3000"
    environment:
      - API_GATEWAY_URL=http://api-gateway:3000
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
